
(ns madra.feidhmchlár.síntiúis
  (:require [Draíoch.stát :as s]
            [Draíoch.bunus :as b]))

;; SÍNTIÚIS GAELAITHE
(b/Sainigh cláraigh-síntiúis! []
           (s/CláraighSíntiús ::paca (b/Feidhm [db _] (:paca db)))
           (s/CláraighSíntiús ::mód (b/Feidhm [db _] (:mód db)))
           (s/CláraighSíntiús ::innéacs-abairte (b/Feidhm [db _] (:innéacs-abairte db)))
           (s/CláraighSíntiús ::innéacs-focail (b/Feidhm [db _] (:innéacs-focail db)))
           (s/CláraighSíntiús ::téacs-clóite (b/Feidhm [db _] (:téacs-clóite db)))
           (s/CláraighSíntiús ::taispeáin-leideanna (b/Feidhm [db _] (:taispeáin-leideanna db)))
           (s/CláraighSíntiús ::tomhais-míchearta (b/Feidhm [db _] (:tomhais-míchearta db)))
           (s/CláraighSíntiús ::réitithe? (b/Feidhm [db _] (:réitithe? db)))

           (s/CláraighSíntiús
            ::cárta-reatha
            (b/Feidhm [db _]
                      (b/Faigh (:paca db) (:innéacs-abairte db))))

           (s/CláraighSíntiús
            ::sprioc-reatha
            (b/Feidhm [db _]
                      (b/Lig [cárta (b/Faigh (:paca db) (:innéacs-abairte db))
                              innéacs (:innéacs-focail db)]
                             (b/Nuair cárta
                                      {:focal (b/Faigh (:gaeilge cárta) innéacs)
                                       :litriúil (b/Faigh (:litriúil cárta) innéacs)})))))
