
(ns madra.feidhmchlár.teagmhais
  (:require [Draíoch.stát :as s]
            [Draíoch.bunus :as b]
            [feidhmchlár.bunachar :as bunachar]))

;; TEAGMHAIS GAELAITHE
(b/Sainigh cláraigh-teagmhais! []

           (s/CláraighTeagmhasBunachar
            ::tús
            (b/Feidhm [_ _]
                      bunachar/bunachar-tosaigh))

           (s/CláraighTeagmhasÉifeacht
            ::lódáil-paca
            (b/Feidhm [_ _]
                      {:madra.feidhmchlár.éifeachtaí/faigh-paca nil}))

           (s/CláraighTeagmhasBunachar
            ::socraigh-paca
            (b/Feidhm [db [_ paca]]
                      (assoc db :paca paca :mód :ag-tógáil :innéacs-abairte 0 :innéacs-focail 0)))

           (s/CláraighTeagmhasÉifeacht
            ::céim-ar-aghaidh
            (b/Feidhm [{:keys [db]} _]
                      (b/Lig [cárta (b/Faigh (:paca db) (:innéacs-abairte db))
                              líon-focal (b/Líon (:gaeilge cárta))
                              innéacs-focail (:innéacs-focail db)]
                             (b/Má (< (inc innéacs-focail) líon-focal)
                                   {:db (assoc db :innéacs-focail (inc innéacs-focail) :téacs-clóite "")}
                                   {:db (assoc db :mód :tráth-na-gceist :téacs-clóite "")
                                    :madra.feidhmchlár.éifeachtaí/cas-fuaim-fx (:sócmhainn-fuaime cárta)}))))

           (s/CláraighTeagmhasBunachar
            ::céad-abairt-eile
            (b/Feidhm [db _]
                      (merge db {:innéacs-abairte (mod (inc (:innéacs-abairte db)) (count (:paca db)))
                                 :innéacs-focail 0
                                 :téacs-clóite ""
                                 :mód :ag-tógáil
                                 :taispeáin-leideanna false
                                 :tomhais-míchearta #{}
                                 :réitithe? false})))

           (s/CláraighTeagmhasBunachar
            ::las-leideanna
            (b/Feidhm [db _]
                      (b/Nuashonraigh db :taispeáin-leideanna not)))

           (s/CláraighTeagmhasÉifeacht
            ::nuashonraigh-téacs
            (b/Feidhm [{:keys [db]} [_ téacs]]
                      (b/Lig [cárta (b/Faigh (:paca db) (:innéacs-abairte db))
                              innéacs (:innéacs-focail db)
                              sprioc (when cárta (b/Faigh (:gaeilge cárta) innéacs))
                              db-nua (assoc db :téacs-clóite téacs)]
                             (b/Má (and sprioc (= téacs sprioc))
                                   {:db db-nua
                                    :dispatch [::céim-ar-aghaidh]}
                                   {:db db-nua}))))

           (s/CláraighTeagmhasÉifeacht
            ::tomhas
            (b/Feidhm [{:keys [db]} [_ rogha]]
                      (b/Lig [cárta (get (:paca db) (:innéacs-abairte db))
                              freagra-ceart (:béarla cárta)
                              is-ceart (= rogha freagra-ceart)]
                             (b/Má is-ceart
                                   {:db (assoc db :réitithe? true)
                                    :dispatch-later {:ms 1000 :dispatch [::céad-abairt-eile]}}
                                   {:db (b/Nuashonraigh db :tomhais-míchearta conj rogha)})))))
