
(ns madra.feidhmchlár.éifeachtaí
  (:require ["package:audioplayers/audioplayers.dart" :as audio]
            ["package:flutter/services.dart" :as services]
            ["dart:convert" :as convert]
            [Draíoch.stát :as s]
            [Draíoch.bunus :as b]
            [feidhmchlár.bunachar :as bunachar]))

;; FÓNTAIS FUAIME
(b/Sainigh cas-fuaim! [cosán-sócmhainne]
           (doto (audio/AudioPlayer)
             (.play (audio/AssetSource cosán-sócmhainne))))

(defn- mapáil-cárta [cárta]
  {:gaeilge (:irish cárta)
   :litriúil (:literals cárta)
   :béarla (:english cárta)
   :roghanna (:options cárta)
   :sócmhainn-fuaime (:audio-asset cárta)})

(b/Sainigh cláraigh-éifeachtaí! []
  ;; Éifeacht: Lódáil an comhad JSON paca.
           (s/CláraighÉifeacht
            ::faigh-paca
            (b/Feidhm [_]
                      (-> services/rootBundle
                          (.loadString "assets/deck.json")
                          (.then (b/Feidhm [json-str]
                                           (b/Lig [sonraí-amha (convert/jsonDecode json-str)
                                                   sonraí-clj (bunachar/tiontú-domhain sonraí-amha)
                                                   paca-gaelaithe (mapv mapáil-cárta sonraí-clj)]
                                                  (s/Seol [:madra.feidhmchlár.teagmhais/socraigh-paca paca-gaelaithe]))))
                          (.catchError (b/Feidhm [earráid]
                                                 (b/Priontáil "Earráid ag lódáil paca:" earráid))))))

  ;; Éifeacht: Seinn comhad fuaime.
           (s/CláraighÉifeacht
            ::cas-fuaim-fx
            (b/Feidhm [cosán-sócmhainne]
                      (cas-fuaim! cosán-sócmhainne))))
