
(ns Draíoch.app
  (:require ["package:flutter/material.dart" :as m]
            [cljd.flutter :as f]))

(defmacro FeidhmchlárÁbhair [& {:keys [teideal téama baile] :as opts}]
  `(m/MaterialApp
    ~@(when (contains? opts :teideal) ['.title teideal])
    ~@(when (contains? opts :téama) ['.theme téama])
    ~@(when (contains? opts :baile) ['.home baile])))

(defmacro SonraíTéama [& {:keys [punannPríomha] :as opts}]
  `(m/ThemeData
    ~@(when (contains? opts :punannPríomha) ['.primarySwatch punannPríomha])))

(defmacro Scafall [& {:keys [corp barra cnaipeSnámh tarraiceán] :as opts}]
  `(m/Scaffold
    ~@(when (contains? opts :corp) ['.body corp])
    ~@(when (contains? opts :barra) ['.appBar barra])
    ~@(when (contains? opts :cnaipeSnámh) ['.floatingActionButton cnaipeSnámh])
    ~@(when (contains? opts :tarraiceán) ['.drawer tarraiceán])))

(defmacro BarraFeidhmchláir [& {:keys [teideal gníomhartha] :as opts}]
  `(m/AppBar
    ~@(when (contains? opts :teideal) ['.title teideal])
    ~@(when (contains? opts :gníomhartha) ['.actions gníomhartha])))

(defmacro Rith [app]
  `(f/run ~app))
