
(ns Draíoch.bunus
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter/services.dart" :as seirbhísí]
            [cljd.flutter :as f]
            [clojure.string :as str]))

;; --- Colors (Dathanna) ---
(def Glas m.Colors/green)
(def Dearg m.Colors/red)
(def Gorm m.Colors/blue)
(def Bán m.Colors/white)
(def Dubh m.Colors/black)
(def Buí m.Colors/yellow)
(def Cian m.Colors/cyan)
(def Maigeanta m.Colors/purpleAccent)
(def Oráiste m.Colors/orange)
(def Liath m.Colors/grey)
(def Corcra m.Colors/purple)
(def Bándearg m.Colors/pink)
(def Ómra m.Colors/amber)
(def Donn m.Colors/brown)
(def Indigó m.Colors/indigo)
(def Aol m.Colors/lime)

;; --- Utils ---
(defmacro Priontáil [& args]
  `(println ~@args))

(defmacro Sainigh [name & body]
  `(defn ~name ~@body))

(defmacro Feidhm [& args]
  `(fn ~@args))

(defmacro LeHaghaidh [& args]
  `(for ~@args))

;; --- State Management ---
(defmacro Adamh [x]
  `(atom ~x))

(defmacro Babhtáil! [& args]
  `(swap! ~@args))

(defmacro Athshocraigh! [& args]
  `(reset! ~@args))

(defmacro Giuirléid [bindings & body]
  `(f/widget ~bindings ~@body))

;; --- Logic (Loighic) ---
(def Fíor true)
(def Bréagach false)

(defmacro Má [& args]
  `(if ~@args))

(defmacro Lig [& args]
  `(let ~@args))

(defmacro Ní [& args]
  `(not ~@args))

(defmacro Agus [& args]
  `(and ~@args))

(defmacro Nó [& args]
  `(or ~@args))

(defmacro Líon [& args]
  `(count ~@args))

(defmacro Socraigh! [& args]
  `(set! ~@args))

(defmacro Déan [& args]
  `(do ~@args))

(defmacro Nuair [& args]
  `(when ~@args))

(defmacro Faigh [& args]
  `(get ~@args))

(defmacro Folamh? [& args]
  `(empty? ~@args))

(def Faic nil)

;; --- Time & Async ---
(defmacro Tréimhse [& {:keys [soicindí milleasoicindí]}]
  `(~'Duration
    ~@(when soicindí ['.seconds soicindí])
    ~@(when milleasoicindí ['.milliseconds milleasoicindí])))

(defmacro Moilligh [tréimhse & body]
  `(~'Future.delayed ~tréimhse (Feidhm [] ~@body)))

;; --- String & Core ---
(defmacro CásUachtair [s]
  `(str/upper-case ~s))

(defmacro CásÍochtair [s]
  `(.toLowerCase ^String ~s))

(defmacro MarThéacs [& args]
  `(str ~@args))

(defmacro Raon [& args]
  `(range ~@args))

(def Nuashonraigh update)
(def Comhcheangail assoc)
(def Méadaigh inc)

;; --- Helper Utils for Focus/Input ---
(defmacro Glan! [rialtóir]
  `(.clear ~rialtóir))

(defmacro IarrFócas! [nód]
  `(.requestFocus ~nód))

(defmacro TaispeáinMéarchlár! []
  `(do
     (.invokeMethod seirbhísí/SystemChannels.textInput "TextInput.show")
     nil))

(defmacro SocraighTéacs! [rialtóir luach]
  `(.-text! ~rialtóir ~luach))
