(ns theme.controller
  (:require [theme.state :as s]
            [theme.tokens :as t]
            ["package:flutter/material.dart" :as m]))

(defn mode-setting [mode]
  (let [light? (= mode :light)]
    (m/ThemeData
     .brightness (if light? m.Brightness/light m.Brightness/dark)
     .primaryColor (if light?
                     (:brand-primary t/colors)
                     (:brand-secondary t/colors))
     .appBarTheme (m/AppBarTheme
                   .backgroundColor (if light?
                                      (:brand-primary t/colors)
                                      (:surface-dark t/colors))
                   .foregroundColor m.Colors/white))))

(defn toggle-mode! []
  (swap! s/state update :mode {:light :dark :dark :light}))
