(ns app.subs
  (:require [hti.re-dash :as rd]))

;; Register all subscriptions.
;; Subscriptions allow UI components to subscribe to changes in the database.
(defn register-subs! []
  ;; Simple subscriptions that directly return values from the db map.
  (rd/reg-sub ::deck (fn [db _] (:deck db)))
  (rd/reg-sub ::mode (fn [db _] (:mode db)))
  (rd/reg-sub ::sentence-idx (fn [db _] (:sentence-idx db)))
  (rd/reg-sub ::word-idx (fn [db _] (:word-idx db)))
  (rd/reg-sub ::typed-text (fn [db _] (:typed-text db)))
  (rd/reg-sub ::show-hints (fn [db _] (:show-hints db)))
  (rd/reg-sub ::quiz-wrong-guesses (fn [db _] (:quiz-wrong-guesses db)))
  (rd/reg-sub ::quiz-solved? (fn [db _] (:quiz-solved? db)))

  ;; Derived Subscription: Current Card
  ;; Calculations can be done inside the subscription to keep the view logic simple.
  (rd/reg-sub
   ::current-card
   (fn [db _]
     (get (:deck db) (:sentence-idx db))))

  ;; Derived Subscription: Current Target Word
  ;; Returns details about the specific word currently being typed.
  (rd/reg-sub
   ::current-target
   (fn [db _]
     (let [card (get (:deck db) (:sentence-idx db))
           idx (:word-idx db)]
       (when card
         ;; Return a small map with just what the UI needs for the current word.
         {:word (get (:irish card) idx)      ;; The Irish word (e.g., "Madra")
          :literal (get (:literals card) idx)}))))) ;; The literal translation (e.g., "Dog")
