(ns draíocht.croí)

(defmacro tús [& body]
  `(defn ~'main []
     ~@body))

(defmacro TRANSLATE__LT [& args]
  `(< ~@args))

(defmacro TRANSLATE__EQ [& args]
  `(= ~@args))

(defmacro TRANSLATE_add_watch [& args]
  `(add-watch ~@args))

(defmacro TRANSLATE_and [& args]
  `(and ~@args))

(defmacro adamh [& args]
  `(atom ~@args))

(defmacro fan [& args]
  `(await ~@args))

(defmacro TRANSLATE_building_view [& args]
  `(building-view ~@args))

(defmacro TRANSLATE_case [& args]
  `(case ~@args))

(defmacro ghabháil [& args]
  `(catch ~@args))

(defmacro TRANSLATE_cond [& args]
  `(cond ~@args))

(defmacro TRANSLATE_contains_QMARK [& args]
  `(contains? ~@args))

(defmacro TRANSLATE_count [& args]
  `(count ~@args))

(defmacro TRANSLATE_current_widget_fn [& args]
  `(current-widget-fn ~@args))

(defmacro TRANSLATE_deep_convert [& args]
  `(deep-convert ~@args))

;; def = definition as Bearla, sain = sainmhíniú anseo
(defmacro sain [& args]
  `(def ~@args))

;; defn = defintion + function  sainf = sainmhíniú + feidhm
(defmacro sainf [& args]
  `(defn ~@args))

(defmacro TRANSLATE_do [& args]
  `(do ~@args))

(defmacro TRANSLATE_doto [& args]
  `(doto ~@args))

(defmacro TRANSLATE_fn [& args]
  `(fn ~@args))

(defmacro TRANSLATE_fn_STAR [& args]
  `(fn* ~@args))

(defmacro TRANSLATE_for [& args]
  `(for ~@args))

(defmacro TRANSLATE_get [& args]
  `(get ~@args))

(defmacro má [& args]
  `(if ~@args))

(defmacro TRANSLATE_inc [& args]
  `(inc ~@args))

(defmacro TRANSLATE_instance_QMARK [& args]
  `(instance? ~@args))

(defmacro TRANSLATE_into [& args]
  `(into ~@args))

(defmacro TRANSLATE_keyword [& args]
  `(keyword ~@args))

(defmacro lig [& args]
  `(let ~@args))

(defmacro TRANSLATE_map [& args]
  `(map ~@args))

(defmacro TRANSLATE_mapv [& args]
  `(mapv ~@args))

(defmacro TRANSLATE_merge [& args]
  `(merge ~@args))

(defmacro TRANSLATE_mod [& args]
  `(mod ~@args))

(defmacro TRANSLATE_name [& args]
  `(name ~@args))

(defmacro TRANSLATE_next_sentence_BANG [& args]
  `(next-sentence! ~@args))

(defmacro TRANSLATE_nil_QMARK [& args]
  `(nil? ~@args))

(defmacro TRANSLATE_not [& args]
  `(not ~@args))

(defmacro TRANSLATE_ns [& args]
  `(ns ~@args))

(defmacro TRANSLATE_println [& args]
  `(println ~@args))

(defmacro TRANSLATE_quiz_view [& args]
  `(quiz-view ~@args))

(defmacro TRANSLATE_range [& args]
  `(range ~@args))

(defmacro TRANSLATE_reset_BANG [& args]
  `(reset! ~@args))

(defmacro TRANSLATE_sequential_QMARK [& args]
  `(sequential? ~@args))

(defmacro TRANSLATE_some__GT [& args]
  `(some-> ~@args))

(defmacro TRANSLATE_str [& args]
  `(str ~@args))

(defmacro TRANSLATE_strip_fadas [& args]
  `(strip-fadas ~@args))

(defmacro TRANSLATE_subvec [& args]
  `(subvec ~@args))

(defmacro TRANSLATE_swap_BANG [& args]
  `(swap! ~@args))

(defmacro TRANSLATE_theme_toggle [& args]
  `(theme-toggle ~@args))

(defmacro triail [& ghabháil]
  `(try ~@(map (fn [form]
                 (if (and (seq? form) (= 'ghabháil (first form)))
                   (cons 'catch (rest form))
                   form))
               ghabháil)))

(defmacro TRANSLATE_vector_QMARK [& args]
  `(vector? ~@args))

(defmacro TRANSLATE_when [& args]
  `(when ~@args))

(defmacro TRANSLATE_when_not [& args]
  `(when-not ~@args))
