
(ns madra.feidhmchlár.bunachar
  (:require ["dart:core" :as core]
            [Draíoch.bunus :as b]))

;; An staid tosaigh dár mbunachar sonraí feidhmchláir.
(def bunachar-tosaigh
  {:paca []
   :innéacs-abairte 0
   :innéacs-focail 0
   :téacs-clóite ""
   :mód :ag-lódáil
   :taispeáin-leideanna false
   :tomhais-míchearta #{}
   :réitithe? false})

;; Convert Dart structures to Clojure structures
(b/Sainigh tiontú-domhain [x]
           (cond
             (vector? x) (mapv tiontú-domhain x)
             (instance? core/Map x) (into {} (map (b/Feidhm [[k v]] [(keyword k) (tiontú-domhain v)]) x))
             (instance? core/List x) (mapv tiontú-domhain x)
             (sequential? x) (mapv tiontú-domhain x)
             :else x))
