(ns main
  (:require
   ["package:flutter/material.dart" :as m]
   [features.lessons.controller :as lessons-ctrl]
   [routing.root :as router]
   [theme.controller :as theme]))

;; The main entry point of the application.
(defn main []
  ;; 1. Initialize Flutter and Theme
  (m/WidgetsFlutterBinding.ensureInitialized)
  (theme/load-mode!)

  ;; 2. Initialize our new domain state and load the deck
  ;;    This replaces all the old re-dash register/dispatch boilerplate!
  (lessons-ctrl/init!)
  (lessons-ctrl/load-deck!)

  ;; 3. Run the Flutter application
  (m/runApp
   (router/view)))
